### PR TITLE
Switch to latest stable DocBook 4.5 DTD

### PR DESCRIPTION
**Pull request by kloczek**
Use freshen DTD version.

### CODE REVIEW

**Comment by kloczek** [comment]
BTW: it would be IMO good to flush currently accumulated +20 commits added 1.4.0 and release new version (1.4.1?)

**Comment by smuellerDD** [comment]
Am Samstag, 29. Juli 2023, 09:23:59 CEST schrieb Tomasz Kłoczko:

Hi Tomasz,

> BTW: it would be IMO good to flush currently accumulated +20 commits added
> 1.4.0 and release new version (1.4.1?)

Yes, I will do that, but there is one more issue I would like to squash.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Applied, thanks.

**Comment by kloczek** [comment]
Thank you 👍 😄

**Pull request closed without merging**
