### PR TITLE
Add support for Travis CI

### PR DESCRIPTION
**Pull request by WOnder93**
This PR prepares the repository for automated testing using [Travis CI](https://travis-ci.org/), which is integrated in GutHub and can be enabled for free for public projects. The PR also fixes a couple of minor issues that prevented testing in the Travis environment properly.

The Travis script builds the code and runs `test/test-invocation.sh`.

Final steps needed to enable Travis for libkcapi:
1. Go to https://travis-ci.org/ and log in using GitHub.
2. Go to your profile page and enable this repository.

Travis will then automatically perform build, cppcheck, and tests on the latest version whenever changes are pushed to a branch, indicating pass/failure in the commit log on GitHub. It will also automatically test new pull requests.

### CODE REVIEW

**Comment by smuellerDD** [comment]
Why do you say that the man target does not exist in the Makefile? I.e. why do you take out the make man test?

**Comment by WOnder93** [comment]
Well, when I ran `make man`, I just got `make: *** No rule to make target 'man'.  Stop.`.

But now I looked deeper into it and I see that it happens only due to the `xmlto` package missing... I will add it to `.travis.yml` and remove that commit, sorry.

**Comment by WOnder93** [comment]
(Please don't merge yet, I will rebase the commits once the Travis run finishes...)

**Comment by WOnder93** [comment]
OK, it should be all good now.

**Comment by smuellerDD** [comment]
All except the clang fix applied. The clang fix is changed to avoid double memset(0) in case the handle is allocated with the regular code path. Thanks.

**Comment by WOnder93** [comment]
Thanks, great! Could you please also do the final steps I outlined in the PR description? It can only be done by the project owner. More info is in the [Travis documentation](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI).

**Comment by smuellerDD** [comment]
Travis-CI integration enabled and working. Thanks.

**Comment by WOnder93** [comment]
The GCC build failed - I believe this is a non-deterministic bug in the old kernel that Travis uses. I ran into this myself several times, restarting the build every time this happens seems to be the only work-around for now (until Travis *finally* decides to update their software...).

**Comment by smuellerDD** [comment]
Am Mittwoch, 14. März 2018, 08:37:24 CET schrieb Ondrej Mosnáček:

Hi Ondrej,

> The GCC build failed - I believe this is a non-deterministic bug in the old
> kernel that Travis uses. I ran into this myself several times, restarting
> the build every time this happens seems to be the only work-around for now
> (until Travis *finally* decides to update their software...).

Thanks for letting me know -- I have never seen that bug. Does the bug always 
happens with AES256 and a file with 65537 bytes?

Note, I test with kernel 4.3.6 and 4.5.0 myself and I did not see that bug. I 
expect that even older kernels work with the library which even would imply 
that potential bugs in the kernel are papered over by the library.

Ciao
Stephan

**Comment by WOnder93** [comment]
I just reproduced it with `while true; do ./kcapi-enc-test.sh || break; done` in a Ubuntu Trusty VM and indeed it seems to happen only at 65537 bytes and always at the `FILEIN / FILEOUT` test... For me it seems to happen for both 128-bit and 256-bit key.

Furthermore, it seems to happen even with newer kernels on Ubuntu 14.04 (on this VM I have 4.9.0-040900 kernel installed because I was testing something). Maybe it is some other element of the Ubuntu 14.04 environment that is causing this? Or some downstream patch in Ubuntu?

**Pull request closed without merging**
