### PR TITLE
build-sys: Use autotools

### PR DESCRIPTION
**Pull request by manoj23**
Use autotools to build the library and the test programs.

The scan target is inspired from [1].

Signed-off-by: Georges Savoundararadj <savoundg@gmail.com>

[1] http://blog.alexrp.com/2013/09/26/clangs-static-analyzer-and-automake/

This commit will ease cross-compilation and integration into other distributions and build systems such as buildroot or Yocto by integrating a standard way of configuring, building and installing the library and the test programs.
I also try to factorize build flags, documentations compilation and I put everything related to compilation in one place.

What do you think?

### CODE REVIEW

**Comment by smuellerDD** [comment]
Hi Georges,

Thanks for helping in the development.

I always refrained from the use of autotools due to the complexity introduced. I see the value of autotools when you have multiple build options. This is not the case for libkcapi. It only has different runtime code paths that are unaffected by the compilation. Thus, what do you think is the benefit apart from having a ./configure invocation?

Ciao
Stephan

**Comment by manoj23** [comment]
Hi Stephan,

I think, using autotools will bring the following the benefits:

1. Cross-compilation

For instance, to compile with the Yocto SDK, you can use the following command:
```
$ source /path/to/environment-setup-armv5e-poky-linux-gnueabi
$ ./configure --host=arm
$ make
```

The first command will set-up the environment correctly (CC, CFLAGS, ARCH, ...) that will be used by the `configure` command.
Without autotools, we would need to modify by hand the Makefile to change the CC variable to use the cross-compiler we want.

2. Integration into distributions and build systems such as buildroot or Yocto

As the build process is always the same (`autoreconf -i && ./configure && make && make install`), it will be easier to integrate the libkcapi in different build processes and in different file system set-up (e.g.: install library in /usr/lib).
To install the library in a specific folder with `configure`, we can use the standard `--prefix` argument instead of modifying the Makefile.

Conclusion: using autotools will just make the build more **portable** across systems and architectures. However, I have only tested this commit with the Yocto SDK use-case described above. I did not write any buildroot or Yocto recipe yet.

Georges

**Comment by smuellerDD** [comment]
Ok, I will integrate your patch.

**Comment by smuellerDD** [comment]
I have now reviewed the patch and I would push it. Yet, it has some shortcomings that I have difficulties in solving. As I am not a wizard in the autoconf stuff, would you mind please giving me a helping hand with the following:

- the libkcapi/ttest code should be able to be compiled twice: once with the native word size and once with -m32 (as it is done with Makefile.m32). I have added a --with-kcapi-test32 that is analogous to --with-kcapi-test that simply adds -m32 to the CFLAGS and LDFLAGS. Yet, it does not work as the library object files need to be recompiled with -m32 as well. I am not sure how to do that with autoconf.

- Would it make sense to create a new directory for the created binaries instead of having them poping up in the root directory (just like the .lib dir for the shared library files)?

- Is the result of a make distclean the state of the repo that should be published for a new version?

- Are the files you provide with the patch the only ones that should be in the git repo? I.e. any resulting files from an autoreconf -i should not be in the git repo (i.e. added to a .gitignore)?

Thanks

**Comment by manoj23** [comment]
1) As the library should be recompiled with the -m32, I think we should add an option named "--enable-m32" that would add the -m32 argument for whole the project (library and binaries).
But, this solution implies to rebuild everything, it is not really practical.
2) As the "make install" rule takes care of installing the binaries in the right place, we should not pay attention to where the binaries are created. But, for cosmetic reason, we can put all the binaries in the same place as follow:
```diff
diff --git a/Makefile.am b/Makefile.am
index 993613e..599a869 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -27,23 +27,23 @@ include_HEADERS = lib/kcapi.h
 bin_PROGRAMS =
 
 if ENABLE_KCAPI_TEST
-bin_PROGRAMS += kcapi
+bin_PROGRAMS += bin/kcapi
 
-kcapi_CPPFLAGS = $(COMMON_CPPFLAGS) -Wno-overlength-strings -pie -fPIE -g -Ilib/
-kcapi_LDFLAGS = $(COMMON_LDFLAGS) -static
-kcapi_LDADD = libkcapi.la
-kcapi_SOURCES = test/kcapi-main.c
+bin_kcapi_CPPFLAGS = $(COMMON_CPPFLAGS) -Wno-overlength-strings -pie -fPIE -g -Ilib/
+bin_kcapi_LDFLAGS = $(COMMON_LDFLAGS) -static
+bin_kcapi_LDADD = libkcapi.la
+bin_kcapi_SOURCES = test/kcapi-main.c
 
 SCAN_FILES += $(kcapi_SOURCES)
 endif
 
 if ENABLE_KCAPI_SPEED
-bin_PROGRAMS += kcapi-speed
+bin_PROGRAMS += bin/kcapi-speed
 
-kcapi_speed_CPPFLAGS = $(COMMON_CPPFLAGS) -pie -fPIE -Wno-variadic-macros -Ilib/
-kcapi_speed_LDFLAGS = $(COMMON_LDFLAGS) -static
-kcapi_speed_LDADD = libkcapi.la
-kcapi_speed_SOURCES = speed-test/cryptoperf.h \
+bin_kcapi_speed_CPPFLAGS = $(COMMON_CPPFLAGS) -pie -fPIE -Wno-variadic-macros -Ilib/
+bin_kcapi_speed_LDFLAGS = $(COMMON_LDFLAGS) -static
+bin_kcapi_speed_LDADD = libkcapi.la
+bin_kcapi_speed_SOURCES = speed-test/cryptoperf.h \
                       speed-test/cryptoperf-aead.c \
                      speed-test/cryptoperf-base.c \
                      speed-test/cryptoperf-hash.c \
@@ -55,12 +55,12 @@ SCAN_FILES += $(kcapi_speed_SOURCES)
 endif
 
 if ENABLE_KCAPI_HASHER
-bin_PROGRAMS += kcapi-hasher
+bin_PROGRAMS += bin/kcapi-hasher
 
-kcapi_hasher_CPPFLAGS = $(COMMON_CPPFLAGS) -fPIC -Ilib/
-kcapi_hasher_LDFLAGS = $(COMMON_LDFLAGS) -static
-kcapi_hasher_LDADD = libkcapi.la
-kcapi_hasher_SOURCES = apps/kcapi-hasher.c
+bin_kcapi_hasher_CPPFLAGS = $(COMMON_CPPFLAGS) -fPIC -Ilib/
+bin_kcapi_hasher_LDFLAGS = $(COMMON_LDFLAGS) -static
+bin_kcapi_hasher_LDADD = libkcapi.la
+bin_kcapi_hasher_SOURCES = apps/kcapi-hasher.c
 
 SCAN_FILES += $(kcapi_hasher_SOURCES)
```
3) I don't think the result of `make distclean` should be published because some automatically generated files such as `configure` or `Makefile.in` are not removed.
4) In my opinion, the files automatically generated by `autoreconf -i` should not be in the git repository.

Regards,

Georges

**Comment by smuellerDD** [comment]
Thanks a lot for the help, patch is merged.

**Pull request closed without merging**
