### PR TITLE
Some further improvements

### PR DESCRIPTION
**Pull request by besser82**
### autotools: Let libtool handle PIC/PIE flags
* With the proper setup libtool will apply the needed flags to build `PIC/PIE` binaries automatically.

### autotools: Use full path for external programs
* Some small changes to find and use external tools with their full path.

### hasher-test: Search for hmaccalc in full $PATH
* Don't rely on `hmaccalc` tools are always present in `/bin`.  They might be somewhere else in `$PATH`.

### CODE REVIEW

**Comment by smuellerDD** [comment]
That patch compiles the code with -fPIC, but not with -fPIE:

$ checksec.sh --file bin/.libs/kcapi-rng 
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE
Full RELRO      Canary found      NX enabled    No PIE          RPATH      No RUNPATH   bin/.libs/kcapi-rng

**Comment by besser82** [comment]
@smuellerDD Should be fixed in rebased commits.

**Comment by besser82** [comment]
> That patch compiles the code with -fPIC, but not with -fPIE:

Sry, I didn't notice that, since on Fedora rpmbuild injects PIE flags automatically and my test gave me a correct, but in general false positive.

**Comment by smuellerDD** [comment]
All applied. Thanks.

**Pull request closed without merging**
