### PR TITLE
CI: Use newer Xenial environment

### PR DESCRIPTION
**Pull request by WOnder93**
This will run tests on a newer kernel (4.15+), increasing test coverage
(mainly support for asynchronous operations).

### CODE REVIEW

**Comment by WOnder93** [comment]
@smuellerDD BTW, I noticed that Travis CI runs are no longer triggered on pushes/ pull request in this repo - did you turn it of intentionally?

**Comment by smuellerDD** [comment]
Am Montag, 20. Mai 2019, 12:47:42 CEST schrieb Ondrej Mosnáček:

Hi Ondrej,

> @smuellerDD BTW, I noticed that Travis CI runs are no longer triggered on
> pushes/ pull request in this repo - did you turn it of intentionally?

No, I did not do anthing here. Strange, do you readily see how to enable it?

Ciao
Stephan

**Comment by WOnder93** [comment]
> No, I did not do anthing here. Strange, do you readily see how to enable it? Ciao Stephan

Hm.. I can see the builds on Travis website [1], just for some reason GitHub doesn't pick them up... I'm not sure how to fix it. I would try clicking "Sync account" on [2] and maybe toggling the libkcapi repo off and on again in Travis. If that doesn't help then you'll probably need to contact GitHub/Travis CI support :(

[1] https://travis-ci.org/smuellerDD/libkcapi
[2] https://travis-ci.org/account/repositories

**Comment by smuellerDD** [comment]
Am Mittwoch, 22. Mai 2019, 10:18:58 CEST schrieb Ondrej Mosnáček:

Hi Ondrej,

> > No, I did not do anthing here. Strange, do you readily see how to enable
> > it? Ciao Stephan
> Hm.. I can see the builds on Travis website [1], just for some reason GitHub
> doesn't pick them up... I'm not sure how to fix it. I would try clicking
> "Sync account" on [2] and maybe toggling the libkcapi repo off and on again
> in Travis. If that doesn't help then you'll probably need to contact
> GitHub/Travis CI support :(
> 
> [1] https://travis-ci.org/smuellerDD/libkcapi
> [2] https://travis-ci.org/account/repositories

Ok, just synced. But it does not help.

I sent an inquiry.

Ciao
Stephan

**Comment by WOnder93** [comment]
@smuellerDD I just tried force-pushing (without change) and there it goes - Travis check showed up :) So whatever was wrong seems fixed now.

**Comment by smuellerDD** [comment]
Am Donnerstag, 23. Mai 2019, 09:00:03 CEST schrieb Ondrej Mosnáček:

Hi Ondrej,

> @smuellerDD I just tried force-pushing (without change) and there it goes -
> Travis check showed up :) So whatever was wrong seems fixed now.

I just got the note that there was a glitch in GitHub which was fixed.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Applied, thanks.

**Pull request closed without merging**
